### ISSUE TITLE
Error when trying to generate deck

### ISSUE THREAD

**Issue by cdaise** [kamui-fin/yt2srs#1]
After fulfilling all the necessary fields, I keep getting an error that pops up when I hit the generate button. I tried generating with/without the "fallback to auto gen subs" on, but it still doesn't work. Once the Anki Error dialog box pops up, I am left with an infinite loading bar. 

<details>
<summary>Debug Information </summary>
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.5
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-06-23 06:59:00
Add-ons possibly involved: ⁨YT Subs2SRS⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Anki2/addons21/1633834851/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/Users/chris/Library/Application Support/Anki2/addons21/1633834851/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Users/chris/Library/Application Support/Anki2/addons21/1633834851/youtube_dl/extractor/youtube.py", line 2762, in _real_extract
    has_videos, playlist = self._extract_playlist(playlist_id)
  File "/Users/chris/Library/Application Support/Anki2/addons21/1633834851/youtube_dl/extractor/youtube.py", line 2685, in _extract_playlist
    raise ExtractorError(message, expected=True)
youtube_dl.utils.ExtractorError: This playlist is private, use --username or --netrc to access it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Anki2/addons21/1633834851/yt_parse.py", line 91, in run
    ydl.download([self.link])
  File "/Users/chris/Library/Application Support/Anki2/addons21/1633834851/youtube_dl/YoutubeDL.py", line 2018, in download
    res = self.extract_info(
  File "/Users/chris/Library/Application Support/Anki2/addons21/1633834851/youtube_dl/YoutubeDL.py", line 820, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/Users/chris/Library/Application Support/Anki2/addons21/1633834851/youtube_dl/YoutubeDL.py", line 620, in report_error
    if not self.params.get('no_color') and self._err_file.isatty() and compat_os_name != 'nt':
AttributeError: 'ErrorHandler' object has no attribute 'isatty'
</details>

**Comment by kamui-fin** [comment]
```
This playlist is private, use --username or --netrc to access it.
```
It appears that you have tried making a deck with a private video. Try it again with one that is public, and it should work out.

**Comment by cdaise** [comment]
> ```
> This playlist is private, use --username or --netrc to access it.
> ```
> 
> It appears that you have tried making a deck with a private video. Try it again with one that is public, and it should work out.

Still doesn't work. While I don't get that private playlist error anymore, I do get another error. This is the video that I was [using](https://www.youtube.com/watch?v=08EaBP1MPak).

<details>
<summary>Error</summary>
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.5
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-06-23 06:59:00
Add-ons possibly involved: ⁨YT Subs2SRS⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Anki2/addons21/1633834851/yt_parse.py", line 91, in run
    ydl.download([self.link])
  File "/Users/chris/Library/Application Support/Anki2/addons21/1633834851/youtube_dl/YoutubeDL.py", line 2018, in download
    res = self.extract_info(
  File "/Users/chris/Library/Application Support/Anki2/addons21/1633834851/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/Users/chris/Library/Application Support/Anki2/addons21/1633834851/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Users/chris/Library/Application Support/Anki2/addons21/1633834851/youtube_dl/extractor/youtube.py", line 1753, in _real_extract
    ytplayer_config = self._get_ytplayer_config(video_id, video_webpage)
  File "/Users/chris/Library/Application Support/Anki2/addons21/1633834851/youtube_dl/extractor/youtube.py", line 1440, in _get_ytplayer_config
    config = self._search_regex(
  File "/Users/chris/Library/Application Support/Anki2/addons21/1633834851/youtube_dl/extractor/common.py", line 991, in _search_regex
    if not self._downloader.params.get('no_color') and compat_os_name != 'nt' and sys.stderr.isatty():
AttributeError: 'ErrorHandler' object has no attribute 'isatty'
</details>

**Comment by kamui-fin** [comment]
This should be fixed now. Here's the new link to the addon:
https://ankiweb.net/shared/info/964531817
