### ISSUE TITLE
Error starting addon

### ISSUE THREAD

**Issue by soliviantar** [kamui-fin/yt2srs#2]
Hi,

I was really excited to try this addon when I found it. There are several YT videos I would love to turn into decks. So I installed it on Anki, but whenver I try to open the addon I get an error. 

Not sure if this is still mantained. I hope it is! Thanks in any case. 

Here's the exception I'm getting:
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-12-06 15:05:05

Caught exception:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1633834851\yt_main.py", line 104, in launch
    screen.setup_ui()
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1633834851\yt_main.py", line 21, in setup_ui
    fields = self.get_fields()
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1633834851\yt_main.py", line 40, in get_fields
    pyjson = json.loads(modeljson)
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by hxse** [comment]
I get error too.

**Comment by kamui-fin** [comment]
This should be fixed now. Here's the new link to the addon: 
https://ankiweb.net/shared/info/964531817
