### ISSUE TITLE
Error Creating Deck

### ISSUE THREAD

**Issue by borreluijken** [kamui-fin/yt2srs#3]
Thank you for creating this addon, i really appreciate it! However, no matter what i do, an error comes up when trying to create a deck. I've read your responses to the other 2 versions of this issue, and i am using the updated version of the addon found at https://ankiweb.net/shared/info/964531817.

video link: https://www.youtube.com/watch?v=M5X_Ijxm2bw

Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-08-19 06:33:55

Caught exception:
Traceback (most recent call last):
  File "C:\Users\<redacted>\AppData\Roaming\Anki2\addons21\964531817\main.py", line 28, in <lambda>
    self.generate_button.clicked.connect(lambda : self.generate())
  File "C:\Users\<redacted>\AppData\Roaming\Anki2\addons21\964531817\main.py", line 77, in generate
    parser.create_subs2srs_deck(**self.config)
AttributeError: module 'parser' has no attribute 'create_subs2srs_deck'

**Comment by kamui-fin** [comment]
Ah, it was because I chose a conflicting name for the worker module. Just pushed an update fixing this. Let me know if it works for you now!

**Comment by borreluijken** [comment]
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨yt2srs⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 211, in loadAddons
  File "C:\Users\redacted\AppData\Roaming\Anki2\addons21\964531817\__init__.py", line 8, in <module>
    from main import launch
  File "C:\Users\redacted\AppData\Roaming\Anki2\addons21\964531817\main.py", line 6, in <module>
    import worker
  File "C:\Users\redacted\AppData\Roaming\Anki2\addons21\964531817\worker.py", line 3, in <module>
    import youtube_dl
  File "C:\Users\redacted\AppData\Roaming\Anki2\addons21\964531817\youtube_dl\__init__.py", line 45, in <module>
    from .YoutubeDL import YoutubeDL
  File "C:\Users\redacted\AppData\Roaming\Anki2\addons21\964531817\youtube_dl\YoutubeDL.py", line 11, in <module>
    import fileinput
ModuleNotFoundError: No module named 'fileinput'

**Comment by kamui-fin** [comment]
So it seems like the standard module `fileinput` isn't already included inside of Anki. I bundled this in the addon, hopefully it works now.

Edit: I just tried it out on a new Windows 10 VM running the latest Anki and it seems to work as expected now.

**Comment by borreluijken** [comment]
It works now, thank you very much!
