### ISSUE TITLE
Still not working in Anki 2.1.60

### ISSUE THREAD

**Issue by shoudairika** [kamui-fin/yt2srs#50]
It doesn't generate the deck we want to. Moreover, it doesn't support Japanese, after I have tried English (somehow the cards end up in other fixed deck. Note: it is not default.)

**Comment by shoudairika** [comment]
U[date:
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-03-13 20:50:22

ERROR: 
[download] Got error: [WinError 10054] An existing connection was forcibly closed by the remote host
Caught exception:
Traceback (most recent call last):
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\worker.py", line 95, in run
    result: YouTubeDownloadResult = YouTubeClient.download_video_files(
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\client_youtube.py", line 69, in download_video_files
    title = YouTubeClient._download_video(video_task, on_progress)
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\client_youtube.py", line 164, in _download_video
    ydl.download([video_task.youtube_video_url])
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\YoutubeDL.py", line 3369, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\YoutubeDL.py", line 3344, in wrapper
    res = func(*args, **kwargs)
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\YoutubeDL.py", line 1507, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\YoutubeDL.py", line 2779, in process_video_result
    self.process_info(new_info)
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\YoutubeDL.py", line 3247, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\YoutubeDL.py", line 2970, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\downloader\common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\downloader\http.py", line 374, in real_download
    for retry in RetryManager(self.params.get('retries'), self.report_retry):
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\utils.py", line 6144, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\downloader\common.py", line 389, in report_retry
    RetryManager.report_retry(
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\utils.py", line 6151, in report_retry
    return error(f'{e}. Giving up after {count - 1} retries') if count > 1 else error(str(e))
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\downloader\common.py", line 392, in <lambda>
    error=IDENTITY if not fatal else lambda e: self.report_error(f'\r[download] Got error: {e}'),
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\YoutubeDL.py", line 1015, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\YoutubeDL.py", line 935, in trouble
    self.to_stderr(message)
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\YoutubeDL.py", line 885, in to_stderr
    self._write_string(f'{self._bidi_workaround(message)}\n', self._out_files.error, only_once=only_once)
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\YoutubeDL.py", line 856, in _write_string
    write_string(message, out=out, encoding=self.params.get('encoding'))
  File "C:\Users\popug\AppData\Roaming\Anki2\addons21\964531817\lib\yt_dlp\utils.py", line 2075, in write_string
    out.flush()
AttributeError: 'ErrorHandler' object has no attribute 'flush'

**Comment by shoudairika** [comment]
Still not create the deck as you described.

**Comment by kamui-fin** [comment]
Hey, did you refresh the deck list by clicking on the "Deck" tab item (or press `d`)?

**Comment by shoudairika** [comment]
I tried, but when the add on reminds me of"Generating cards" it stuck to 0% then go to the cards are created without any progress recording... It doesn't create the cards at all...

**Comment by kamui-fin** [comment]
Which video link are you using to test? And you mentioned you were using Anki 2.1.60? Which operating system are you using?

**Comment by shoudairika** [comment]
https://www.youtube.com/watch?v=QySjGUMZdTM&t=255s  I used Anki 2.1.60 qt 6 version windows 11.

**Comment by kamui-fin** [comment]
Hey, could you update the addon and try again? I think it should be fixed now.
