### ISSUE TITLE
Cannot import name 'launch' from 'main' 

### ISSUE THREAD

**Issue by ghost** [kamui-fin/yt2srs#6]
When loading '⁨yt2srs⁩':
⁨Traceback (most recent call last):
  File "/home/yaoberh/pyenv/lib/python3.9/site-packages/aqt/addons.py", line 239, in loadAddons
    __import__(addon.dir_name)
  File "/home/yaoberh/.local/share/Anki2/addons21/964531817/__init__.py", line 8, in <module>
    from main import launch
ImportError: cannot import name 'launch' from 'main' (/home/yaoberh/.local/share/Anki2/addons21/1186808928/main.py)

**Comment by stanislaw** [comment]
This might be not actual anymore? 🤔
